apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: railway-attrition-api
  name: railway-attrition-api
spec:
  selector:
    matchLabels:
      app: railway-attrition-api
  template:
    metadata:
      labels:
        app: railway-attrition-api
    spec:
      containers:
        - image: ${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: railway-attrition-api
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: railway-attrition-api
  name: railway-attrition-api
spec:
  ports:
    - protocol: "TCP"
      port: 5000
      targetPort: 5000
  selector:
    app: railway-attrition-api
  type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: railway-attrition-api
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: railway-attrition-api
                port:
                  number: 5000
